name: ai_framework
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0.0
  - pytorch>=2.0.0
  - torchvision
  - cudatoolkit=11.8  # For GPU support, modify as needed for your hardware
  - scikit-learn>=1.2.0
  - numpy>=1.22.0
  - pandas>=2.0.0
  - matplotlib>=3.6.0
  - nltk>=3.8.1
  - spacy>=3.5.0
  - tqdm>=4.65.0
  - requests>=2.28.0
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - evaluate>=0.4.0
    - langchain>=0.0.312  # Updated version
    - langchain-core>=0.1.0  # Added core package 
    - langfair>=0.1.0  # May need to install from source if not available via pip
    - sentence-transformers>=2.2.0  # For embeddings in bias analysis
    - conformal>=0.2.0
    - mapie>=0.7.0
    - huggingface-hub>=0.16.0
    - accelerate>=0.21.0  # For faster transformers inference
    - tensorboard>=2.12.0  # For visualization
    - ipython  # For interactive testing
    - pytest  # For unit testing
    - black  # For code formatting
    - jupyter  # For notebook interface
